board/urls.py
from django.urls import path

from . import views

app_name='board'
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:mainpost_id>',views.detail,name='detail'),
    path('mainpost_create',views.mainpost_create,name='create'),
    path('comment_create/<int:mainpost_id>', views.comment_create, name='comment_create' ),
    path('mainpost_delete/<int:mainpost_id>',views.mainpost_delete,name='mainpost_delete'),
    path('mainpost_modify/<int:mainpost_id>',views.mainpost_modify, name='mainpost_modify'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='common'
urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
    path('mypage/',views.mypage,name='mypage'),
    path('signup/id_check',views.id_check,name='id_check')
]

config/urls.py
from operator import index
from django.contrib import admin
from django.urls import path,include
from common.views import * 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('',mainpage,name='mainpage'),
    path('common/',include('common.urls')),
]

board/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Mainpost(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    def __str__(self):
        return self.title

class Comment(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    mainpost=models.ForeignKey(Mainpost,on_delete=models.CASCADE)
    text=models.TextField()
    created_date=models.DateTimeField(
        default=timezone.now()
    )

common/models.py
from django.db import models

# Create your models here.

board/forms.py
from dataclasses import field
from tkinter import Widget
from django import forms
from .models import *

class MainpostForm(forms.ModelForm):
    class Meta:
        model=Mainpost
        fields=['title','text']
      
        labels={
            'title':'제목',
            'text':'내용',
        }

class CommentForm(forms.ModelForm):
    class meta:
        model=Comment
        field=['text']
        labels={
            
            'text':'내용'
        }

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    # email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

board/views.py
from django.contrib import messages
from django.shortcuts import redirect, render,get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# from django.http import HttpResponse
# Create your views here.

# def index(request): #글 목록페이지
#     mainpost_list= Mainpost.objects.order_by('-created_date')

#     context={'mainpost_list':mainpost_list}
#     return render(request,'board/mainpost_list.html',context)

def index(request): #글 목록페이지
    page=request.GET.get('page','1')
    mainpost_list= Mainpost.objects.order_by('-created_date')
    paginator=Paginator(mainpost_list,10)

    page_obj=paginator.get_page(page)

    context={'mainpost_list':page_obj, 'page':page}
    return render(request,'board/mainpost_list.html',context)

def detail(request, mainpost_id): #글 상세페이지
    mainpost=get_object_or_404(Mainpost,pk=mainpost_id)
    context={'mainpost':mainpost}
    return render(request,'board/mainpost_detail.html',context)

@login_required(login_url='common:login')
def mainpost_create(request):  #글쓰기
    if request.method =='POST':
        form=MainpostForm(request.POST)
        if form.is_valid():
            mainpost=form.save(commit=False)
            mainpost.author=request.user
            mainpost.save()
            return redirect('board:index')

    else:
        form=MainpostForm()
    return render(request,'board/mainpost_form.html',{'form':form})

@login_required
def mainpost_delete(request,mainpost_id):
    mainpost=get_object_or_404(Mainpost,pk=mainpost_id)
    if request.user != mainpost.author:
        messages.error(request,'작성자가아닙니다')
        return redirect('board:detail',mainpost_id=mainpost.id)
    mainpost.delete()
    return redirect('board:index')

@login_required
def mainpost_modify(request,mainpost_id):
    mainpost=get_object_or_404(Mainpost,pk=mainpost_id)
    if request.user != mainpost.author:
        messages.error(request, '작성자가 아닙니다')
        return redirect('board:detail',mainpost_id=mainpost.id)
    if request.method=='POST':
        form =MainpostForm(request.POST, instance=mainpost)
        if form.is_valid():
            mainpost=form.save(commit=False)
            mainpost.save()
            return redirect('board:detail',mainpost_id=mainpost.id)
    else:
        form=MainpostForm(instance=mainpost)
    context={'form':form}
    return render(request,'board/mainpost_form.html',context)



@login_required(login_url='common:login')
def comment_create(request,mainpost_id):
    if request.method=='POST':
        mainpost=get_object_or_404(Mainpost,pk=mainpost_id)
        mainpost.comment_set.create(text=request.POST.get('text'),created_date=timezone.now(),author=request.user)
        return redirect('board:detail',mainpost_id=mainpost.id)

common/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from common.forms import UserForm

# Create your views here.

def mainpage(request):
    return render(request,'common/index.html')

def mypage(request):

    return render(request,'common/mypage.html')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            # login(request, user)  # 로그인
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

def id_check(request):
    try:
        user=User.objects.get(username=request.GET['username'])
       
    except:
        user=None
    result={
        'result':'success',
        'data': 'exist' if user else 'not exist'
    }
    
    return JsonResponse(result)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <!--header-->
    {% include "navbar.html" %}

        {% block content %}
        <!--삽입내용-->
        {% endblock %}
       
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <script src="{% static 'clock.js' %}"></script>
        
        {% block script %}
        
                <!--삽입할스크립트-->
        {% endblock %}
        

</body>
</html>

templates/board/mainpost_detail.html
{% extends 'base.html' %} {% block title %} 글 상세보기 {% endblock %} {% block content %}

<div class="container my-3">
  <div class="card my-3">
    <p class="fs-4"><span class="material-icons">person </span>{{ mainpost.author }} <span class="material-icons fs-5"> history </span> {{ mainpost.created_date }}</p>


    <div class="card-text">
      <p class="fs-1 fw-bold">{{ mainpost.title }}</p>
      <p>{{ mainpost.text|linebreaksbr }}</p>
    </div>
    <div class="fs-6 m-0">
      <span class="material-icons fs-6 text-danger"> thumb_up_alt </span>
      <span class="text-danger">0</span>
      <span class="material-icons fs-6"> comment </span>
      <span>{{ mainpost.comment_set.count }}</span>
    </div>
    <div class="my-3">
      {% if request.user == mainpost.author %}
      <a href="{% url 'board:mainpost_modify' mainpost.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
      <a href="{% url 'board:mainpost_delete' mainpost.id %}" class="btn btn-sm btn-danger btn-outline-secondary" style="color: white">삭제</a>
      {% endif %}
    </div>

    <div class=" my-3 mb-0">
      <form method="post" action="{% url 'board:comment_create' mainpost.id %}" class="my-3">
        {% csrf_token %} {% include 'form_errors.html' %}
     
          <textarea name="text" class="form-control md-9" rows="2" {% if not user.is_authenticated %} disabled placeholder="로그인 후 이용 가능" {% else %} placeholder="댓글을 입력해주세요!" {% endif %}></textarea>
          
     
        <input type="submit" class="btn btn-primary justify-content-end" value="등록" />
      </form>
    </div>

    <div class="card my-3 m-0">
    {% for comment in mainpost.comment_set.all %}
    
      <div class="card">
        <div class="card-text">
          <p class="fs-4"><span class="material-icons">person </span>{{ comment.author }} <span class="material-icons fs-5"> history </span> {{ comment.created_date }}</p>

          <p>{{ comment.text }}</p>
        </div>
      </div>
    

    {% endfor %}
  </div>
  </div>
</div>
{% endblock %} 
{% block script %} {% endblock %}

templates/board/mainpost_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 >글쓰기</h1>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="title" >제목</label>
            <input type="text"  name="title" 
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="text" >내용</label>
            <textarea  name="text"
                      rows="10">{{ form.text.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit">저장하기</button>
    </form>
{% endblock %}

templates/board/mainpost_list.html
{% extends 'base.html' %}
 {% block content %}
<div class="container my-3">

  <h1>대충 게시판</h1>
  <div class="col-6">
    <a href="{% url 'board:create' %}" class="btn btn-dark">글쓰기</a>
  </div>
  <table class="table">
    <thead>
    <tr class="table-primary ">
        <th>번호</th>
        <th style="width: 50%">제목</th>
        <th>작성자</th>
        <th>
          작성시간
          </th>
    </tr>
    </thead>
    <tbody>
    
    {% for mainpost in mainpost_list %}
    <tr class="">
        <!-- <td>{{ forloop.counter }}</td> -->
        <td>{{ mainpost.id }}</td>
        <td>
            <a href="{% url 'board:detail' mainpost.id %}">{{ mainpost.title }}</a>
            {% if mainpost.comment_set.count > 0 %}
            <span class="text-danger small mx-2">댓글:{{ mainpost.comment_set.count }}</span>
            {% endif %}
        </td>
        <td>{{ mainpost.author }}</td>
        <td>{{ mainpost.created_date }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    

    <ul class="pagination justify-content-center">
      <!--이전-->
      {% if mainpost_list.has_previous %} <!--다음 페이지가 있다면-->
     <li class="page-item">
      <a class="page-link" href="?page={{ mainpost_list.previous_page_number }}">이전</a>
     </li>
     {% else %}
     <li class="page-item-disabled" >
      <a class="page-link" style="background-color: #E2E2E2;">이전</a>
     </li>
     {% endif %}

     <!--리스트-->
     {% for page_number in mainpost_list.paginator.page_range %}
     {% if page_number >= mainpost_list.number|add:-5 and page_number <= mainpost_list.number|add:5 %}
     {% if page_number == mainpost_list.number %}
     <li class="page-item active" aria-current="page">
      <a class="page-link"  href="?page={{ page_number }}">{{ page_number }}</a>
     </li>
     {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
      {% endif %}
      {% endfor %}
        <!-- 다음 -->
        {% if mainpost_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ mainpost_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" style="background-color: #E2E2E2;"tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}

templates/common/index.html
{% extends 'base.html' %}
 {% block title %} MAIN {% endblock %} 
 {% block content%}
 
<h1 class="my-3  text-center">MAINPAGE</h1>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card text-white bg-dark mb-3" style="width: 18rem;">
        <span class="material-icons ">
          grid_view
          </span>
        <div class="card-body">
          <h4 class="card-title text-center">익명 계시판</h4>
          <p class="card-text">궁금한게 있으면 물어보고, 불만있으면 욕할 수 있는 계시판</p>
          <a href="{% url 'board:index' %}" class="btn btn-light ">계시판 바로가기</a>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card  bg-warning mb-3" style="width: 18rem;">
        <span class="material-icons">
          warning
          </span>
        <div class="card-body">
          <h4 class="card-title text-center">뭐해야되지</h4>
          <p class="card-text">뭐해야되지</p>
          <a href="{% url 'board:index' %}" class="btn btn-light ">뭐해야되지</a>
        </div>
      </div>
    </div>
 
 
  </div>
</div>
  {% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
{% include "form_errors.html" %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    <div class="col-md-12 text-center">
       
            아직 회원이 나니신가요?
        <h2> <a href="{% url 'common:signup' %}">회원가입하러가기</a></h2>
    </div>
    
    
</div>
{% endblock %}

templates/common/mypage.html
{% extends 'base.html' %}
{% block title %} abc {% endblock %} 
{% block content %}

<div class="container my-3">
    <h1><b> {{ user }}'s page</b></h1> 
</div>
최근 로그인 : {{ user.last_login }}


{% endblock %}

{% block script %}

{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 회원가입 {% endblock %} 
{% block content %}
<div class="container my-3">
    <form id="ff" method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">아이디</label>
            <input  type="text" class="form-control" name="username" id="username" 
                   value="{{ form.username.value|default_if_none:'' }}">
                   <p id="username_warning">아직 입력되지 않았습니다</p>
                   <input id="btn" type="button" value="아이디중복체크"> <span id="idcheck">중복체크를 해 주세요</span>
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" 
                   value="{{ form.password1.value|default_if_none:'' }}">
                   <p id="p1_warning">아직 입력되지 않았습니다</p>


        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" 
                   value="{{ form.password2.value|default_if_none:'' }}">
                   <p id="p2_warning">아직 입력되지 않았습니다</p>

        </div>
        <div class="mb-3">
           
        <button  type="button" id="submit-button" class="btn btn-primary" >생성하기</button>
    </form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'common/signup.js' %}"></script>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
  <!-- message 표시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul>
      <li>{{ message.message }}</li>
    </ul>
    {% endfor %}
  </div>
  {% endif %} {% for field in form %}
  <!-- 필드 오류 -->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %} {% endfor %}
  <!-- 넌필드 오류 -->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mainpage' %}"
      ><b><var>FUKING_KDT</var></b></a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDarkDropdown"
      aria-controls="navbarNavDarkDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDarkDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ user.username }}
          </a>
          <ul
            class="dropdown-menu dropdown-menu-dark"
            aria-labelledby="navbarDarkDropdownMenuLink"
          >
            <li>
              <a class="dropdown-item" href="{% url 'common:mypage' %}"
                >내 정보</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'common:logout' %}"
                >로그아웃</a
              >
            </li>
            <li><a class="dropdown-item" href="#">배고파</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:login' %}"> 로그인 </a>
        </li>
       
        
        {% endif %}
     
      </ul>
    </div>
    </div>
    <div class="container-fluid justify-content-end" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"id="clock">00:00</a>         
        </li>
        </ul>
    </div>
         
</nav>